version: '2'
services:
  openvpn-client: 
    build: dockerfiles/openvpn-client
    command: openvpn --config /client/rich.ovpn
    privileged: true
    extra_hosts:
    - "vpn.my.fqdn:172.31.8.4"
    volumes:
    - ./client:/client
